name: course_app
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/profile.svg

      
